# Site settings

author: Tyex
email: taamyjipyjam@outlook.com
twitter_username: twitter
github_username:  tyex2004
googleplus_username: google

head-title: Tyex的个人网站
title: Tyex的个人网站

baseurl: ""    # the subpath of your site, "/blog"
url: ""

# footer 
description: 我是一名来自广州的高中生，擅长魔方、乒乓球、物理、音乐伴奏和安排交通路线。我也是游戏模组开发组织ECMSC的会长，目前正在开发OpenBVE的一些模组。<br>

favo: "欢迎来到我的个人网站！"
descrpt: "在这里，我会分享我的开发经验、学习经验和生活点滴在博客上。"


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "indigo lighten-1"
head-theme-color: "#5c6bc0"     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "indigo lighten-1"
footer-button-color: "indigo lighten-2"
footer-link-color: "red-text text-accent-1"

share-button-color: "pink"
share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

